import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/layout/Sidebar";
import { BottomNav } from "@/components/layout/BottomNav";
import { TopNav } from "@/components/layout/TopNav";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { ErrorBoundary } from "@/components/errors/ErrorBoundary";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-100`}
      >
        <ErrorBoundary>
          <AuthProvider>
            {/* Desktop Sidebar - hidden on mobile */}
            <div className="hidden md:block">
              <Sidebar />
            </div>
            
            {/* Mobile Top Nav - hidden on desktop */}
            <TopNav />
            
            {/* Main Content */}
            <main className="md:ml-64 min-h-screen pb-20 md:pb-0">
              <div className="max-w-md mx-auto md:max-w-none md:mx-0">
                {children}
              </div>
            </main>
            
            {/* Mobile Bottom Nav - hidden on desktop */}
            <BottomNav />
          </AuthProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
